// <auto-generated />
//-----------------------------------------------------------------------
// <copyright file="ResourceKeys.cs" company="Talegen, LLC">
//     Copyright (c) Talegen, LLC. All rights reserved.
// </copyright>
//-----------------------------------------------------------------------
namespace Bastille.Id.Core.Properties
{
    /// <summary>
    /// This class is automatically generated and will create resource keys for use within the application.
    /// </summary>
    public static class ResourceKeys
    {
        /// <summary>
        /// Gets the key for the default_template_en_htm resource string.
        /// </summary>
        public const string default_template_en_htm = "default_template_en_htm"; 

        /// <summary>
        /// Gets the key for the default_template_en_txt resource string.
        /// </summary>
        public const string default_template_en_txt = "default_template_en_txt"; 

        /// <summary>
        /// Gets the key for the ErrorAccessDeniedText resource string.
        /// </summary>
        public const string ErrorAccessDeniedText = "ErrorAccessDeniedText"; 

        /// <summary>
        /// Gets the key for the ErrorClientNotFoundText resource string.
        /// </summary>
        public const string ErrorClientNotFoundText = "ErrorClientNotFoundText"; 

        /// <summary>
        /// Gets the key for the ErrorGroupNameExistsText resource string.
        /// </summary>
        public const string ErrorGroupNameExistsText = "ErrorGroupNameExistsText"; 

        /// <summary>
        /// Gets the key for the ErrorGroupNotFoundText resource string.
        /// </summary>
        public const string ErrorGroupNotFoundText = "ErrorGroupNotFoundText"; 

        /// <summary>
        /// Gets the key for the ErrorGroupSpecifyOwnerText resource string.
        /// </summary>
        public const string ErrorGroupSpecifyOwnerText = "ErrorGroupSpecifyOwnerText"; 

        /// <summary>
        /// Gets the key for the ErrorOrganizationNotFoundText resource string.
        /// </summary>
        public const string ErrorOrganizationNotFoundText = "ErrorOrganizationNotFoundText"; 

        /// <summary>
        /// Gets the key for the ErrorRecordNotFoundText resource string.
        /// </summary>
        public const string ErrorRecordNotFoundText = "ErrorRecordNotFoundText"; 

        /// <summary>
        /// Gets the key for the ErrorUserIdentityNotFoundText resource string.
        /// </summary>
        public const string ErrorUserIdentityNotFoundText = "ErrorUserIdentityNotFoundText"; 

        /// <summary>
        /// Gets the key for the ErrorUserNotFoundText resource string.
        /// </summary>
        public const string ErrorUserNotFoundText = "ErrorUserNotFoundText"; 

        /// <summary>
        /// Gets the key for the LabelChangePasswordText resource string.
        /// </summary>
        public const string LabelChangePasswordText = "LabelChangePasswordText"; 

        /// <summary>
        /// Gets the key for the LabelConfirmPasswordText resource string.
        /// </summary>
        public const string LabelConfirmPasswordText = "LabelConfirmPasswordText"; 

        /// <summary>
        /// Gets the key for the LabelNewPasswordText resource string.
        /// </summary>
        public const string LabelNewPasswordText = "LabelNewPasswordText"; 

        /// <summary>
        /// Gets the key for the PrompGroupCreateSuccessText resource string.
        /// </summary>
        public const string PrompGroupCreateSuccessText = "PrompGroupCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimCreateFailText resource string.
        /// </summary>
        public const string PromptClientClaimCreateFailText = "PromptClientClaimCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientClaimCreateSuccessText = "PromptClientClaimCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimDeleteFailText resource string.
        /// </summary>
        public const string PromptClientClaimDeleteFailText = "PromptClientClaimDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientClaimDeleteSuccessText = "PromptClientClaimDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimExistsFailText resource string.
        /// </summary>
        public const string PromptClientClaimExistsFailText = "PromptClientClaimExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimNotFoundFailText resource string.
        /// </summary>
        public const string PromptClientClaimNotFoundFailText = "PromptClientClaimNotFoundFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimUpdateFailText resource string.
        /// </summary>
        public const string PromptClientClaimUpdateFailText = "PromptClientClaimUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientClaimUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientClaimUpdateSuccessText = "PromptClientClaimUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientCreateFailureText resource string.
        /// </summary>
        public const string PromptClientCreateFailureText = "PromptClientCreateFailureText"; 

        /// <summary>
        /// Gets the key for the PromptClientCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientCreateSuccessText = "PromptClientCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientDeleteFailureText resource string.
        /// </summary>
        public const string PromptClientDeleteFailureText = "PromptClientDeleteFailureText"; 

        /// <summary>
        /// Gets the key for the PromptClientDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientDeleteSuccessText = "PromptClientDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeCreateFailText resource string.
        /// </summary>
        public const string PromptClientGrantTypeCreateFailText = "PromptClientGrantTypeCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientGrantTypeCreateSuccessText = "PromptClientGrantTypeCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeDeleteFailText resource string.
        /// </summary>
        public const string PromptClientGrantTypeDeleteFailText = "PromptClientGrantTypeDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientGrantTypeDeleteSuccessText = "PromptClientGrantTypeDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeExistsFailText resource string.
        /// </summary>
        public const string PromptClientGrantTypeExistsFailText = "PromptClientGrantTypeExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeUpdateFailText resource string.
        /// </summary>
        public const string PromptClientGrantTypeUpdateFailText = "PromptClientGrantTypeUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientGrantTypeUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientGrantTypeUpdateSuccessText = "PromptClientGrantTypeUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientIdExistsText resource string.
        /// </summary>
        public const string PromptClientIdExistsText = "PromptClientIdExistsText"; 

        /// <summary>
        /// Gets the key for the PromptClientIdRequiredText resource string.
        /// </summary>
        public const string PromptClientIdRequiredText = "PromptClientIdRequiredText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutCreateFailText resource string.
        /// </summary>
        public const string PromptClientLogoutCreateFailText = "PromptClientLogoutCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientLogoutCreateSuccessText = "PromptClientLogoutCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutDeleteFailText resource string.
        /// </summary>
        public const string PromptClientLogoutDeleteFailText = "PromptClientLogoutDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientLogoutDeleteSuccessText = "PromptClientLogoutDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutExistsFailText resource string.
        /// </summary>
        public const string PromptClientLogoutExistsFailText = "PromptClientLogoutExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutUpdateFailText resource string.
        /// </summary>
        public const string PromptClientLogoutUpdateFailText = "PromptClientLogoutUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientLogoutUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientLogoutUpdateSuccessText = "PromptClientLogoutUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginCreateFailText resource string.
        /// </summary>
        public const string PromptClientOriginCreateFailText = "PromptClientOriginCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientOriginCreateSuccessText = "PromptClientOriginCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginDeleteFailText resource string.
        /// </summary>
        public const string PromptClientOriginDeleteFailText = "PromptClientOriginDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientOriginDeleteSuccessText = "PromptClientOriginDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginExistsFailText resource string.
        /// </summary>
        public const string PromptClientOriginExistsFailText = "PromptClientOriginExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginUpdateFailText resource string.
        /// </summary>
        public const string PromptClientOriginUpdateFailText = "PromptClientOriginUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientOriginUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientOriginUpdateSuccessText = "PromptClientOriginUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyCreateFailText resource string.
        /// </summary>
        public const string PromptClientPropertyCreateFailText = "PromptClientPropertyCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientPropertyCreateSuccessText = "PromptClientPropertyCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyDeleteFailText resource string.
        /// </summary>
        public const string PromptClientPropertyDeleteFailText = "PromptClientPropertyDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientPropertyDeleteSuccessText = "PromptClientPropertyDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyExistsFailText resource string.
        /// </summary>
        public const string PromptClientPropertyExistsFailText = "PromptClientPropertyExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyUpdateFailText resource string.
        /// </summary>
        public const string PromptClientPropertyUpdateFailText = "PromptClientPropertyUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientPropertyUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientPropertyUpdateSuccessText = "PromptClientPropertyUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectCreateFailText resource string.
        /// </summary>
        public const string PromptClientRedirectCreateFailText = "PromptClientRedirectCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientRedirectCreateSuccessText = "PromptClientRedirectCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectDeleteFailText resource string.
        /// </summary>
        public const string PromptClientRedirectDeleteFailText = "PromptClientRedirectDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientRedirectDeleteSuccessText = "PromptClientRedirectDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectExistsFailText resource string.
        /// </summary>
        public const string PromptClientRedirectExistsFailText = "PromptClientRedirectExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectUpdateFailText resource string.
        /// </summary>
        public const string PromptClientRedirectUpdateFailText = "PromptClientRedirectUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientRedirectUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientRedirectUpdateSuccessText = "PromptClientRedirectUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeCreateFailText resource string.
        /// </summary>
        public const string PromptClientScopeCreateFailText = "PromptClientScopeCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientScopeCreateSuccessText = "PromptClientScopeCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeDeleteFailText resource string.
        /// </summary>
        public const string PromptClientScopeDeleteFailText = "PromptClientScopeDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientScopeDeleteSuccessText = "PromptClientScopeDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeExistsFailText resource string.
        /// </summary>
        public const string PromptClientScopeExistsFailText = "PromptClientScopeExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeUpdateFailText resource string.
        /// </summary>
        public const string PromptClientScopeUpdateFailText = "PromptClientScopeUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientScopeUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientScopeUpdateSuccessText = "PromptClientScopeUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretCreateFailText resource string.
        /// </summary>
        public const string PromptClientSecretCreateFailText = "PromptClientSecretCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretCreateSuccessText resource string.
        /// </summary>
        public const string PromptClientSecretCreateSuccessText = "PromptClientSecretCreateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretDeleteFailText resource string.
        /// </summary>
        public const string PromptClientSecretDeleteFailText = "PromptClientSecretDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretDeleteSuccessText resource string.
        /// </summary>
        public const string PromptClientSecretDeleteSuccessText = "PromptClientSecretDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretExistsFailText resource string.
        /// </summary>
        public const string PromptClientSecretExistsFailText = "PromptClientSecretExistsFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretUpdateFailText resource string.
        /// </summary>
        public const string PromptClientSecretUpdateFailText = "PromptClientSecretUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptClientSecretUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientSecretUpdateSuccessText = "PromptClientSecretUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptClientUpdateFailureText resource string.
        /// </summary>
        public const string PromptClientUpdateFailureText = "PromptClientUpdateFailureText"; 

        /// <summary>
        /// Gets the key for the PromptClientUpdateSuccessText resource string.
        /// </summary>
        public const string PromptClientUpdateSuccessText = "PromptClientUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptGroupCreateFailText resource string.
        /// </summary>
        public const string PromptGroupCreateFailText = "PromptGroupCreateFailText"; 

        /// <summary>
        /// Gets the key for the PromptGroupDeleteFailText resource string.
        /// </summary>
        public const string PromptGroupDeleteFailText = "PromptGroupDeleteFailText"; 

        /// <summary>
        /// Gets the key for the PromptGroupDeleteSuccessText resource string.
        /// </summary>
        public const string PromptGroupDeleteSuccessText = "PromptGroupDeleteSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptGroupUpdateFailText resource string.
        /// </summary>
        public const string PromptGroupUpdateFailText = "PromptGroupUpdateFailText"; 

        /// <summary>
        /// Gets the key for the PromptGroupUpdateSuccessText resource string.
        /// </summary>
        public const string PromptGroupUpdateSuccessText = "PromptGroupUpdateSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptNewAndConfirmPasswordAreNeededText resource string.
        /// </summary>
        public const string PromptNewAndConfirmPasswordAreNeededText = "PromptNewAndConfirmPasswordAreNeededText"; 

        /// <summary>
        /// Gets the key for the PromptNewAndConfirmPasswordMustMatchText resource string.
        /// </summary>
        public const string PromptNewAndConfirmPasswordMustMatchText = "PromptNewAndConfirmPasswordMustMatchText"; 

        /// <summary>
        /// Gets the key for the PromptPasswordRequirementsText resource string.
        /// </summary>
        public const string PromptPasswordRequirementsText = "PromptPasswordRequirementsText"; 

        /// <summary>
        /// Gets the key for the PromptProfileUpdatedFailText resource string.
        /// </summary>
        public const string PromptProfileUpdatedFailText = "PromptProfileUpdatedFailText"; 

        /// <summary>
        /// Gets the key for the PromptProfileUpdatedSuccessfullyText resource string.
        /// </summary>
        public const string PromptProfileUpdatedSuccessfullyText = "PromptProfileUpdatedSuccessfullyText"; 

        /// <summary>
        /// Gets the key for the PromptUserCreatedFailedText resource string.
        /// </summary>
        public const string PromptUserCreatedFailedText = "PromptUserCreatedFailedText"; 

        /// <summary>
        /// Gets the key for the PromptUserCreatedSuccessText resource string.
        /// </summary>
        public const string PromptUserCreatedSuccessText = "PromptUserCreatedSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptUserDeletedFailedText resource string.
        /// </summary>
        public const string PromptUserDeletedFailedText = "PromptUserDeletedFailedText"; 

        /// <summary>
        /// Gets the key for the PromptUserDeletedSuccessText resource string.
        /// </summary>
        public const string PromptUserDeletedSuccessText = "PromptUserDeletedSuccessText"; 

        /// <summary>
        /// Gets the key for the PromptUserUpdatedFailedText resource string.
        /// </summary>
        public const string PromptUserUpdatedFailedText = "PromptUserUpdatedFailedText"; 

        /// <summary>
        /// Gets the key for the PromptUserUpdatedSuccessText resource string.
        /// </summary>
        public const string PromptUserUpdatedSuccessText = "PromptUserUpdatedSuccessText"; 

        /// <summary>
        /// Gets the key for the reset_password_en_htm resource string.
        /// </summary>
        public const string reset_password_en_htm = "reset_password_en_htm"; 

        /// <summary>
        /// Gets the key for the reset_password_en_txt resource string.
        /// </summary>
        public const string reset_password_en_txt = "reset_password_en_txt"; 

        /// <summary>
        /// Gets the key for the StorageConfigurationNotSpecifiedErrorText resource string.
        /// </summary>
        public const string StorageConfigurationNotSpecifiedErrorText = "StorageConfigurationNotSpecifiedErrorText"; 

        /// <summary>
        /// Gets the key for the verify_account_en_htm resource string.
        /// </summary>
        public const string verify_account_en_htm = "verify_account_en_htm"; 

        /// <summary>
        /// Gets the key for the verify_account_en_txt resource string.
        /// </summary>
        public const string verify_account_en_txt = "verify_account_en_txt"; 
    }
}
