//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bastille.Id.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bastille.Id.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied..
        /// </summary>
        public static string ErrorAccessDeniedText {
            get {
                return ResourceManager.GetString("ErrorAccessDeniedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A client was not found with the {0} &quot;{1}&quot;..
        /// </summary>
        public static string ErrorClientNotFoundText {
            get {
                return ResourceManager.GetString("ErrorClientNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group with the name &quot;{0}&quot; already exists..
        /// </summary>
        public static string ErrorGroupNameExistsText {
            get {
                return ResourceManager.GetString("ErrorGroupNameExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A group was not found with the {0} &quot;{1}&quot;..
        /// </summary>
        public static string ErrorGroupNotFoundText {
            get {
                return ResourceManager.GetString("ErrorGroupNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid owner Identity was not specified for the group..
        /// </summary>
        public static string ErrorGroupSpecifyOwnerText {
            get {
                return ResourceManager.GetString("ErrorGroupSpecifyOwnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An organization was not found with the {0} &quot;{1}&quot;..
        /// </summary>
        public static string ErrorOrganizationNotFoundText {
            get {
                return ResourceManager.GetString("ErrorOrganizationNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record was not found with the specified identity..
        /// </summary>
        public static string ErrorRecordNotFoundText {
            get {
                return ResourceManager.GetString("ErrorRecordNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user with identity &quot;{0}&quot;..
        /// </summary>
        public static string ErrorUserIdentityNotFoundText {
            get {
                return ResourceManager.GetString("ErrorUserIdentityNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string ErrorUserNotFoundText {
            get {
                return ResourceManager.GetString("ErrorUserNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string LabelChangePasswordText {
            get {
                return ResourceManager.GetString("LabelChangePasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string LabelConfirmPasswordText {
            get {
                return ResourceManager.GetString("LabelConfirmPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string LabelNewPasswordText {
            get {
                return ResourceManager.GetString("LabelNewPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added new group &quot;{0}&quot; with Id {1}..
        /// </summary>
        public static string PrompGroupCreateSuccessText {
            get {
                return ResourceManager.GetString("PrompGroupCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt failed to create new client with Id {0} and name {1}..
        /// </summary>
        public static string PromptClientCreateFailureText {
            get {
                return ResourceManager.GetString("PromptClientCreateFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a new client with an Id {0} and name {1}..
        /// </summary>
        public static string PromptClientCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt failed to delete client with Id {0} and name {1}..
        /// </summary>
        public static string PromptClientDeleteFailureText {
            get {
                return ResourceManager.GetString("PromptClientDeleteFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted client with Id {0} and name {1}..
        /// </summary>
        public static string PromptClientDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new grant type &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientGrantTypeCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added grant type &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientGrantTypeCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete grant type &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientGrantTypeDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted grant type &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientGrantTypeDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grant type &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientGrantTypeExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update grant type &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientGrantTypeUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated grant type &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientGrantTypeUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientGrantTypeUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Client Id &quot;{0}&quot; already exists..
        /// </summary>
        public static string PromptClientIdExistsText {
            get {
                return ResourceManager.GetString("PromptClientIdExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A unique Client Id value is required..
        /// </summary>
        public static string PromptClientIdRequiredText {
            get {
                return ResourceManager.GetString("PromptClientIdRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new logout URI &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientLogoutCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientLogoutCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added logout URI &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientLogoutCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientLogoutCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete logout URI &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientLogoutDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientLogoutDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted logout URI &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientLogoutDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientLogoutDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logout URI &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientLogoutExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientLogoutExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update logout URI &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientLogoutUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientLogoutUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated logout URI &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientLogoutUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientLogoutUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new origin &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientOriginCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientOriginCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added origin &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientOriginCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientOriginCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete origin &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientOriginDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientOriginDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted origin &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientOriginDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientOriginDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The origin &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientOriginExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientOriginExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update origin &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientOriginUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientOriginUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated origin &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientOriginUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientOriginUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new property &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientPropertyCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientPropertyCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added property &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientPropertyCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientPropertyCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete property &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientPropertyDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientPropertyDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted property &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientPropertyDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientPropertyDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientPropertyExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientPropertyExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update property &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientPropertyUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientPropertyUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated property &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientPropertyUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientPropertyUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new redirect URI &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientRedirectCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientRedirectCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added redirect URI &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientRedirectCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientRedirectCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete redirect URI &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientRedirectDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientRedirectDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted redirect URI &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientRedirectDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientRedirectDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The redirect URI &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientRedirectExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientRedirectExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update redirect URI &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientRedirectUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientRedirectUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated redirect URI &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientRedirectUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientRedirectUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new scope &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientScopeCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientScopeCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added scope &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientScopeCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientScopeCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete scope &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientScopeDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientScopeDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted scope &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientScopeDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientScopeDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scope &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientScopeExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientScopeExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update scope &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientScopeUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientScopeUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated scope &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientScopeUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientScopeUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to add new secret of type &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientSecretCreateFailText {
            get {
                return ResourceManager.GetString("PromptClientSecretCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added secret of type &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientSecretCreateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientSecretCreateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete secret of type &quot;{0}&quot; in Client with Id {1} failed..
        /// </summary>
        public static string PromptClientSecretDeleteFailText {
            get {
                return ResourceManager.GetString("PromptClientSecretDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted secret of type &quot;{0}&quot; in Client with Id {1}..
        /// </summary>
        public static string PromptClientSecretDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptClientSecretDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The secret specified of type &quot;{0}&quot; already exists for Client with Id {1}..
        /// </summary>
        public static string PromptClientSecretExistsFailText {
            get {
                return ResourceManager.GetString("PromptClientSecretExistsFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update secret of type &quot;{0}&quot; for Client with Id {1} failed..
        /// </summary>
        public static string PromptClientSecretUpdateFailText {
            get {
                return ResourceManager.GetString("PromptClientSecretUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated secret of type &quot;{0}&quot; to Client with Id {1}..
        /// </summary>
        public static string PromptClientSecretUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientSecretUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt failed to update client with Id {0} and name {1}..
        /// </summary>
        public static string PromptClientUpdateFailureText {
            get {
                return ResourceManager.GetString("PromptClientUpdateFailureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated client with Id {0} and name {1}..
        /// </summary>
        public static string PromptClientUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptClientUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to create new group &quot;{0}&quot; failed..
        /// </summary>
        public static string PromptGroupCreateFailText {
            get {
                return ResourceManager.GetString("PromptGroupCreateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to delete group &quot;{0}&quot; with Id {1} failed..
        /// </summary>
        public static string PromptGroupDeleteFailText {
            get {
                return ResourceManager.GetString("PromptGroupDeleteFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted group {0} {1}..
        /// </summary>
        public static string PromptGroupDeleteSuccessText {
            get {
                return ResourceManager.GetString("PromptGroupDeleteSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to update group &quot;{0}&quot; with Id {1} failed..
        /// </summary>
        public static string PromptGroupUpdateFailText {
            get {
                return ResourceManager.GetString("PromptGroupUpdateFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated group {0} {1}..
        /// </summary>
        public static string PromptGroupUpdateSuccessText {
            get {
                return ResourceManager.GetString("PromptGroupUpdateSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password are needed..
        /// </summary>
        public static string PromptNewAndConfirmPasswordAreNeededText {
            get {
                return ResourceManager.GetString("PromptNewAndConfirmPasswordAreNeededText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password must match..
        /// </summary>
        public static string PromptNewAndConfirmPasswordMustMatchText {
            get {
                return ResourceManager.GetString("PromptNewAndConfirmPasswordMustMatchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords must be 8-20 characters, contain one lower case letter, one upper case letter, one number, and one special character. Passwords must not contain spaces or emoji..
        /// </summary>
        public static string PromptPasswordRequirementsText {
            get {
                return ResourceManager.GetString("PromptPasswordRequirementsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile update for user {0}:{1} failed..
        /// </summary>
        public static string PromptProfileUpdatedFailText {
            get {
                return ResourceManager.GetString("PromptProfileUpdatedFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Updated Successfully.
        /// </summary>
        public static string PromptProfileUpdatedSuccessfullyText {
            get {
                return ResourceManager.GetString("PromptProfileUpdatedSuccessfullyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt Failed to create a new user with details: Email: {0}.
        /// </summary>
        public static string PromptUserCreatedFailedText {
            get {
                return ResourceManager.GetString("PromptUserCreatedFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created a new user with details: Email: {0} Id: {1}.
        /// </summary>
        public static string PromptUserCreatedSuccessText {
            get {
                return ResourceManager.GetString("PromptUserCreatedSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt Failed to delete a user with details: Email: {0}: Id: {1}.
        /// </summary>
        public static string PromptUserDeletedFailedText {
            get {
                return ResourceManager.GetString("PromptUserDeletedFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted user with details: Email: {0} Id: {1}.
        /// </summary>
        public static string PromptUserDeletedSuccessText {
            get {
                return ResourceManager.GetString("PromptUserDeletedSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt Failed to update user with details: Email: {0} Id: {1}.
        /// </summary>
        public static string PromptUserUpdatedFailedText {
            get {
                return ResourceManager.GetString("PromptUserUpdatedFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated a user with these details: Email: {0} Id: {1}.
        /// </summary>
        public static string PromptUserUpdatedSuccessText {
            get {
                return ResourceManager.GetString("PromptUserUpdatedSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Reset Your Password&lt;/title&gt;
        ///    &lt;style&gt;
        ///
        ///        body, html {
        ///            padding: 0;
        ///            margin: 0;
        ///            font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///            font-size: 16px;
        ///            color: black;
        ///            background-color: whitesmoke;
        ///        }
        ///
        ///        body,
        ///        html, 
        ///        .body {
        ///          background: #f3f3f3 !important;
        ///        }
        ///
        ///        .header {
        ///          background: #f3f3f3;
        ///        }
        ///
        ///        #heade [rest of string was truncated]&quot;;.
        /// </summary>
        public static string reset_password_en_htm {
            get {
                return ResourceManager.GetString("reset_password_en_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FIRSTNAME$,
        ///
        ///We received a request to reset your password. 
        ///
        ///To reset your password, please click the following link below to complete the password reset process:
        ///
        ///$LINK$
        ///
        ///If you did not request a password reset, please contact us..
        /// </summary>
        public static string reset_password_en_txt {
            get {
                return ResourceManager.GetString("reset_password_en_txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;Reset Your Password&lt;/title&gt;
        ///    &lt;style&gt;
        ///
        ///        body, html {
        ///            padding: 0;
        ///            margin: 0;
        ///            font-family: &apos;Segoe UI&apos;, Tahoma, Geneva, Verdana, sans-serif;
        ///            font-size: 16px;
        ///            color: black;
        ///            background-color: whitesmoke;
        ///        }
        ///
        ///        #header {
        ///            height: 64px;
        ///        }
        ///
        ///        #logo {
        ///            padding: 0;
        ///            height: 64px;
        ///            width: 182px;
        ///        }
        ///
        ///        #conta [rest of string was truncated]&quot;;.
        /// </summary>
        public static string verify_account_en_htm {
            get {
                return ResourceManager.GetString("verify_account_en_htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $FIRSTNAME$,
        ///
        ///Please click the link below to verify your e-mail address and activate your account.
        ///
        ///$LINK$.
        /// </summary>
        public static string verify_account_en_txt {
            get {
                return ResourceManager.GetString("verify_account_en_txt", resourceCulture);
            }
        }
    }
}
